name: 'CI'

description: 'Build and test source code. Generate documentation.'

inputs:
  node-version:  # e.g. '16'
    description: 'The node version to use'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js v${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - run: npm ci
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm run test
      shell: bash
    - run: npm run doc
      shell: bash
