name: Merge into Master

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      # TODO
      - master
      - switch-travis-to-github-actions
  workflow_dispatch:

env:
  NODE_VERSION: '16'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run CI
        id: ci
        uses: ./.github/actions/ci
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: tar -czf docs.tar.gz docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./docs.tar.gz
          if-no-files-found: error
          retention-days: 1

  # TODO At the moment we just deploy the doc to github pages. It is semi-OK
  # that we update the doc on each push to master. However, in the future our
  # deployment should probably publish the package to npm. This requires a real
  # release with version and so on. So in the future the deploy setup must
  # change.
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v3
        with:
          name: docs

      - run: tar -xf docs.tar.gz

      - name: Deploy Doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          # For this to work the GITHUB_TOKEN needs read/write permissions. See
          # the action-settings in github!
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # TODO Temporarily we use gh-pages-2 instead of gh-pages until next
          # release. If everything turns out to work fine, we come back to
          # gh-pages.
          publish_branch: gh-pages-2
          publish_dir: ./docs
