name: Merge into Master

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
#    tags:
#      # TODO
#      # We use tags of the form x.y.z to mark releases.
#      - '[0-9]+\.[0-9]+\.[0-9]+'
    branches:
      # TODO
      - master
      - switch-travis-to-github-actions
  workflow_dispatch:

# github.ref_name
# github.ref_type
# github.ref

env:
  NODE_VERSION: '16'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run doc

      - run: tar -czf docs.tar.gz docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./docs.tar.gz
          if-no-files-found: error
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
#    if: 'true'

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v3
        with:
          name: docs

      - run: tar -xf docs.tar.gz

      - name: Deploy Doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          # For this to work the GITHUB_TOKEN needs read/write permissions. See
          # the action-settings in github!
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Temporarily we use gh-pages-2 instead of gh-pages until next
          # release.
          publish_branch: gh-pages-2
          publish_dir: ./docs
